"""
Конфигурация вариантов для экзаменационных заданий.
Каждый вариант имеет свою тематику и названия моделей.
"""

VARIANTS = {
    1: {
        'theme': 'Магазин обуви',
        'app_name': 'products',
        'main_model': 'Product',
        'main_model_verbose': 'Товар',
        'main_model_plural': 'Товары',
        'category_model': 'Category',
        'category_verbose': 'Категория',
        'category_plural': 'Категории',
        'manufacturer_model': 'Manufacturer',
        'manufacturer_verbose': 'Производитель',
        'manufacturer_plural': 'Производители',
        'supplier_model': 'Supplier',
        'supplier_verbose': 'Поставщик',
        'supplier_plural': 'Поставщики',
        'unit_model': 'Unit',
        'unit_verbose': 'Единица измерения',
        'unit_plural': 'Единицы измерения',
        'order_model': 'Order',
        'order_verbose': 'Заказ',
        'order_plural': 'Заказы',
        'order_status_model': 'OrderStatus',
        'order_status_verbose': 'Статус заказа',
        'order_status_plural': 'Статусы заказов',
        'pickup_point_model': 'PickupPoint',
        'pickup_point_verbose': 'Пункт выдачи',
        'pickup_point_plural': 'Пункты выдачи',
        'order_item_model': 'OrderItem',
        'order_item_verbose': 'Позиция заказа',
        'order_item_plural': 'Позиции заказов',
        'site_name': 'Магазин обуви',
        'site_title': 'Система управления товарами',
        'nav_products': 'Товары',
        'nav_orders': 'Заказы',
        'button_add': 'Добавить товар',
        'button_add_order': 'Добавить заказ',
        'page_title_list': 'Список товаров',
        'page_title_orders': 'Список заказов',
    },
    2: {
        'theme': 'Книжный магазин',
        'app_name': 'books',
        'main_model': 'Book',
        'main_model_verbose': 'Книга',
        'main_model_plural': 'Книги',
        'category_model': 'Genre',
        'category_verbose': 'Жанр',
        'category_plural': 'Жанры',
        'manufacturer_model': 'Publisher',
        'manufacturer_verbose': 'Издательство',
        'manufacturer_plural': 'Издательства',
        'supplier_model': 'Supplier',
        'supplier_verbose': 'Поставщик',
        'supplier_plural': 'Поставщики',
        'unit_model': 'Unit',
        'unit_verbose': 'Единица измерения',
        'unit_plural': 'Единицы измерения',
        'order_model': 'Order',
        'order_verbose': 'Заказ',
        'order_plural': 'Заказы',
        'order_status_model': 'OrderStatus',
        'order_status_verbose': 'Статус заказа',
        'order_status_plural': 'Статусы заказов',
        'pickup_point_model': 'PickupPoint',
        'pickup_point_verbose': 'Пункт выдачи',
        'pickup_point_plural': 'Пункты выдачи',
        'order_item_model': 'OrderItem',
        'order_item_verbose': 'Позиция заказа',
        'order_item_plural': 'Позиции заказов',
        'site_name': 'Книжный магазин',
        'site_title': 'Система управления книгами',
        'nav_products': 'Книги',
        'nav_orders': 'Заказы',
        'button_add': 'Добавить книгу',
        'button_add_order': 'Добавить заказ',
        'page_title_list': 'Список книг',
        'page_title_orders': 'Список заказов',
    },
    3: {
        'theme': 'Магазин электроники',
        'app_name': 'products',
        'main_model': 'Product',
        'main_model_verbose': 'Товар',
        'main_model_plural': 'Товары',
        'category_model': 'Category',
        'category_verbose': 'Категория',
        'category_plural': 'Категории',
        'manufacturer_model': 'Brand',
        'manufacturer_verbose': 'Бренд',
        'manufacturer_plural': 'Бренды',
        'supplier_model': 'Supplier',
        'supplier_verbose': 'Поставщик',
        'supplier_plural': 'Поставщики',
        'unit_model': 'Unit',
        'unit_verbose': 'Единица измерения',
        'unit_plural': 'Единицы измерения',
        'order_model': 'Order',
        'order_verbose': 'Заказ',
        'order_plural': 'Заказы',
        'order_status_model': 'OrderStatus',
        'order_status_verbose': 'Статус заказа',
        'order_status_plural': 'Статусы заказов',
        'pickup_point_model': 'PickupPoint',
        'pickup_point_verbose': 'Пункт выдачи',
        'pickup_point_plural': 'Пункты выдачи',
        'order_item_model': 'OrderItem',
        'order_item_verbose': 'Позиция заказа',
        'order_item_plural': 'Позиции заказов',
        'site_name': 'Магазин электроники',
        'site_title': 'Система управления товарами',
        'nav_products': 'Товары',
        'nav_orders': 'Заказы',
        'button_add': 'Добавить товар',
        'button_add_order': 'Добавить заказ',
        'page_title_list': 'Список товаров',
        'page_title_orders': 'Список заказов',
    },
    4: {
        'theme': 'Аптека',
        'app_name': 'medicines',
        'main_model': 'Medicine',
        'main_model_verbose': 'Лекарство',
        'main_model_plural': 'Лекарства',
        'category_model': 'Category',
        'category_verbose': 'Категория',
        'category_plural': 'Категории',
        'manufacturer_model': 'Manufacturer',
        'manufacturer_verbose': 'Производитель',
        'manufacturer_plural': 'Производители',
        'supplier_model': 'Supplier',
        'supplier_verbose': 'Поставщик',
        'supplier_plural': 'Поставщики',
        'unit_model': 'Unit',
        'unit_verbose': 'Единица измерения',
        'unit_plural': 'Единицы измерения',
        'order_model': 'Order',
        'order_verbose': 'Заказ',
        'order_plural': 'Заказы',
        'order_status_model': 'OrderStatus',
        'order_status_verbose': 'Статус заказа',
        'order_status_plural': 'Статусы заказов',
        'pickup_point_model': 'PickupPoint',
        'pickup_point_verbose': 'Пункт выдачи',
        'pickup_point_plural': 'Пункты выдачи',
        'order_item_model': 'OrderItem',
        'order_item_verbose': 'Позиция заказа',
        'order_item_plural': 'Позиции заказов',
        'site_name': 'Аптека',
        'site_title': 'Система управления лекарствами',
        'nav_products': 'Лекарства',
        'nav_orders': 'Заказы',
        'button_add': 'Добавить лекарство',
        'button_add_order': 'Добавить заказ',
        'page_title_list': 'Список лекарств',
        'page_title_orders': 'Список заказов',
    },
    5: {
        'theme': 'Магазин одежды',
        'app_name': 'products',
        'main_model': 'Product',
        'main_model_verbose': 'Товар',
        'main_model_plural': 'Товары',
        'category_model': 'Category',
        'category_verbose': 'Категория',
        'category_plural': 'Категории',
        'manufacturer_model': 'Brand',
        'manufacturer_verbose': 'Бренд',
        'manufacturer_plural': 'Бренды',
        'supplier_model': 'Supplier',
        'supplier_verbose': 'Поставщик',
        'supplier_plural': 'Поставщики',
        'unit_model': 'Unit',
        'unit_verbose': 'Единица измерения',
        'unit_plural': 'Единицы измерения',
        'order_model': 'Order',
        'order_verbose': 'Заказ',
        'order_plural': 'Заказы',
        'order_status_model': 'OrderStatus',
        'order_status_verbose': 'Статус заказа',
        'order_status_plural': 'Статусы заказов',
        'pickup_point_model': 'PickupPoint',
        'pickup_point_verbose': 'Пункт выдачи',
        'pickup_point_plural': 'Пункты выдачи',
        'order_item_model': 'OrderItem',
        'order_item_verbose': 'Позиция заказа',
        'order_item_plural': 'Позиции заказов',
        'site_name': 'Магазин одежды',
        'site_title': 'Система управления товарами',
        'nav_products': 'Товары',
        'nav_orders': 'Заказы',
        'button_add': 'Добавить товар',
        'button_add_order': 'Добавить заказ',
        'page_title_list': 'Список товаров',
        'page_title_orders': 'Список заказов',
    },
    6: {
        'theme': 'Продуктовый магазин',
        'app_name': 'products',
        'main_model': 'Product',
        'main_model_verbose': 'Товар',
        'main_model_plural': 'Товары',
        'category_model': 'Category',
        'category_verbose': 'Категория',
        'category_plural': 'Категории',
        'manufacturer_model': 'Manufacturer',
        'manufacturer_verbose': 'Производитель',
        'manufacturer_plural': 'Производители',
        'supplier_model': 'Supplier',
        'supplier_verbose': 'Поставщик',
        'supplier_plural': 'Поставщики',
        'unit_model': 'Unit',
        'unit_verbose': 'Единица измерения',
        'unit_plural': 'Единицы измерения',
        'order_model': 'Order',
        'order_verbose': 'Заказ',
        'order_plural': 'Заказы',
        'order_status_model': 'OrderStatus',
        'order_status_verbose': 'Статус заказа',
        'order_status_plural': 'Статусы заказов',
        'pickup_point_model': 'PickupPoint',
        'pickup_point_verbose': 'Пункт выдачи',
        'pickup_point_plural': 'Пункты выдачи',
        'order_item_model': 'OrderItem',
        'order_item_verbose': 'Позиция заказа',
        'order_item_plural': 'Позиции заказов',
        'site_name': 'Продуктовый магазин',
        'site_title': 'Система управления товарами',
        'nav_products': 'Товары',
        'nav_orders': 'Заказы',
        'button_add': 'Добавить товар',
        'button_add_order': 'Добавить заказ',
        'page_title_list': 'Список товаров',
        'page_title_orders': 'Список заказов',
    },
}

def get_variant(variant_number):
    """Получить конфигурацию варианта по номеру"""
    if variant_number not in VARIANTS:
        raise ValueError(f"Вариант {variant_number} не существует. Доступны варианты: {list(VARIANTS.keys())}")
    return VARIANTS[variant_number]

def list_variants():
    """Получить список всех доступных вариантов"""
    return [(num, config['theme']) for num, config in VARIANTS.items()]